apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bnzw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bnzw
    app.kubernetes.io/part-of: tkrw-pr712-0075-0060-app
  name: devfile-sample-bnzw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bnzw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bnzw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-bnzw@sha256:0714320ad3aa2b6bb192899afbf7ecf0e1a1a3c2fc1d8fc4c0c90ce37cda1ae8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
